[package]
name = "smtlib"
version = "0.1.6"
edition = "2021"
description = "A high-level API for interacting with SMT solvers"
homepage = "https://github.com/oeb25/smtlib-rs/tree/main/smtlib"
license = "MIT/Apache-2.0"
authors = ["Oliver Bøving <oliver@bvng.dk>"]
readme = "README.md"
repository = "https://github.com/oeb25/smtlib-rs"
documentation = "https://docs.rs/smtlib"

[features]
default = []
serde = ["dep:serde", "smtlib-lowlevel/serde"]
z3 = ["smtlib-lowlevel/z3"]
z3-static = ["smtlib-lowlevel/z3-static"]
cvc5 = ["smtlib-lowlevel/cvc5"]
const-bit-vec = []
async = ["smtlib-lowlevel/async"]

[dependencies]
itertools = "0.10.5"
miette = { version = "5.5.0", features = ["fancy"] }
thiserror = "1.0.38"
smtlib-lowlevel = { path = "../lowlevel", version = "0.1.5" }
serde = { version = "1.0.152", features = ["derive"], optional = true }
num-bigint = "0.4.3"
regex = "1.9.1"
num-traits = "0.2.15"

[dev-dependencies]
insta = { version = "1.23.0", features = ["ron"] }
miette = { version = "5.5.0", features = ["fancy"] }
smtlib = { path = ".", features = [
    "serde",
    "z3",
    "z3-static",
    "cvc5",
    "const-bit-vec",
    "async",
] }

[build-dependencies]
smtlib-build-util = { version = "0.1.0", path = "../build-util" }
smtlib-lowlevel = { version = "0.1.5", path = "../lowlevel" }

[package.metadata.docs.rs]
all-features = true
